### ISSUE TITLE
Data not passed the same way i expect

### ISSUE THREAD

**Issue by benzen** [caolan/magery#12]
It seams to me that groovy-magery and js-magery doesn't  render the same way for this kind of exemple.
Don't know we is wrong.

```html
<template data-tagname="my-app">
  <app-title></app-title>
  oups
  <app-button text="minus" onclick="decrement()"></app-button>
  {{counter}}
  <app-button text="plus" onclick="increment()"></app-button>
</template>

<template data-tagname="app-button">
  <button>{{text}}</button>
</template>

<template data-tagname="app-title">
  <h1>{{title}}</h1>
</template>
```

```json
{
    "name": "World",
    "counter": 0,
    "title": "abc"
}
```

Here is the render I've got (using the example editor app).
![capture d ecran 2018-01-15 a 11 29 52](https://user-images.githubusercontent.com/139909/34952388-84bef074-f9e7-11e7-851a-26976d9851fc.png)

Here is what i expected, which is also what groovy-magery produce
![capture d ecran 2018-01-15 a 11 30 59 1](https://user-images.githubusercontent.com/139909/34952429-ae13706c-f9e7-11e7-95e4-ba40db1ae80b.png)

Since groovy magery is more or less a direct translation of python-magery I assume python-magery will produce the same output.

**Comment by caolan** [comment]
This is the way it used to work - which is probably why python-magery still behaves like this. I changed the javascript library so you have to explicitly pass down properties instead. This will make it easier for us to optimise rendering performance later on, and I think makes it easier to track where your template data is coming from too.

I'm happy to discuss the merits of each approach, however.

**Comment by benzen** [comment]
It a not clear to me how do you see the case of a page full of template.
I think that would be hard to pass all the data down to the smallest component in the page.
How do you see an implementation of this kind of thing ?

**Comment by benzen** [comment]
I m not aware of optimization that could be unlock with this change. Can you explain how the template will be optimized ?
What if we split the context in two.
First the context that come from attributes and second the data that come from the main data in the top component

**Comment by caolan** [comment]
by reducing the context data to only the properties used by the sub-template, it makes it easier for us to skip rendering when using immutable data structures

**Comment by benzen** [comment]
Make sense, I'll open an issue/pr on magery-tests for this case

**Comment by benzen** [comment]
There is a pr for this
