### ISSUE TITLE
Miss behavior when attribute is "newT"

### ISSUE THREAD

**Issue by benzen** [caolan/magery#15]
Here is an exemple
```html
<template data-tagname="my-app">
    <todo-input newT="{{newT}}"></todo-input>
</template>

<template data-tagname="todo-input">
    <input type="text" value="{{newT}}"/>
</template>
```
```json
{
    "newT":"alpha"
}
```

**Comment by benzen** [comment]
When the property is "newT",  the input don't get any value.
When i change the property name every where for "new", the input get it's value as expected.

**Comment by caolan** [comment]
Attribute names are automatically converted to lowercase by the browser: https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute

That means {{ newt }} would work but {{ newT }} would not.

It's a bit of an inconvenient restriction in our case, but I don't see much we can do about it.

**Comment by caolan** [comment]
If there is some way we can detect it, it would be nice to give a compile-time warning / error.

**Comment by benzen** [comment]
Ok this make sense
If I remember correctly what react do, they force user to use camel case name and when it’s required they convert it to dashed case.

The first step in my opinion is to document it. Maybe it starting to make sense to create a dedicated site for Margery the language/idea this site would have links to all implementation of course.

I m pretty sure we can see it at compile time.
I’ll come up with a test case.

Benjamin Dreux

**Comment by benzen** [comment]
we now have a test case in the suite for this.
