### ISSUE TITLE
Examples do not work (Magery.initTemplates is not a function)

### ISSUE THREAD

**Issue by jamesrom** [caolan/magery#2]
There appears to be an issue with minification or maybe the examples haven't been updated.

In chrome, open: https://caolan.github.io/magery/examples/hello-world.html

Start developer tools and find:
![image](https://user-images.githubusercontent.com/539129/29399108-3ae2bbc2-836b-11e7-8c38-6e8f5e22d1dc.png)

**Comment by caolan** [comment]
Yes, sorry - the syntax is in flux again. I'll get the examples updated for you soon! I think the live editor is working but the docs are not up to date with the new syntax anyway so it's probably not much use to you.

**Comment by caolan** [comment]
The README and examples have now been updated to the new API.
